In [1]:
import torch

Tensors : is a multidimensional matrix containing elements of a single data type

In [2]:
x = torch.empty(1)

In [3]:
x

tensor([-4.8218e-34])

In [4]:
x = torch.empty(3)
x

tensor([1.0887e-36, 0.0000e+00, 0.0000e+00])

In [6]:
x = torch.empty(2,3)
x

tensor([[5.0876e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
x = torch.empty(2,2,3)
x

tensor([[[6.0721e-35, 0.0000e+00, 0.0000e+00],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[7.3909e+22, 7.5555e+31, 7.0736e+31],
         [1.7237e+25, 6.3828e+28, 3.8016e-39]]])

In [8]:
x = torch.rand(5,3)

In [9]:
x

tensor([[0.5154, 0.4774, 0.4894],
        [0.0191, 0.0964, 0.5016],
        [0.0491, 0.8153, 0.2540],
        [0.1086, 0.0603, 0.3366],
        [0.9157, 0.3747, 0.4382]])

In [11]:
x = torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
x.size(),x.shape

(torch.Size([5, 3]), torch.Size([5, 3]))

In [14]:
print(x.dtype)

torch.float32


In [15]:
x = torch.tensor([5,3])

In [16]:
x

tensor([5, 3])

In [17]:
x = torch.ones(2,2)
y = torch.rand(2,2)
z = x+y
z

tensor([[1.7885, 1.1356],
        [1.3158, 1.3617]])

In [18]:
torch.add(x,y)

tensor([[1.7885, 1.1356],
        [1.3158, 1.3617]])

In [19]:
y.add_(x)

tensor([[1.7885, 1.1356],
        [1.3158, 1.3617]])

We can also subtract, divide and multiply

### Slicing

In [22]:
M = torch.rand(5,3)
print(M)

print(M[0:3,[0,2]])

tensor([[0.6153, 0.0887, 0.9963],
        [0.4520, 0.0610, 0.3625],
        [0.9038, 0.8513, 0.3795],
        [0.8348, 0.1981, 0.9554],
        [0.2034, 0.3508, 0.9294]])
tensor([[0.6153, 0.9963],
        [0.4520, 0.3625],
        [0.9038, 0.3795]])


In [23]:
M[1,1].item()

0.0609668493270874

In [24]:
x = torch.rand(4,4)
z = x.view(-1,8)
z

tensor([[0.8596, 0.1970, 0.2749, 0.3691, 0.6849, 0.0684, 0.2905, 0.5946],
        [0.7891, 0.1217, 0.1102, 0.4055, 0.1561, 0.3629, 0.7847, 0.6003]])

In [25]:
import numpy as np

In [26]:
a = torch.empty(5)
b = a.numpy()

In [28]:
print(a,"\n",b)

tensor([6.1014e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]) 
 [6.1014074e-35 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]


In [30]:
a = np.ones(5)
b = torch.from_numpy(a) #will share the same memory as a
#SO that any modification on a will affect b
c = torch.tensor(a)

print(a,"\n",b,"\n",c)

[1. 1. 1. 1. 1.] 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### GPU support

In [31]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [32]:
device

device(type='cpu')

In [33]:
x = torch.empty(5).to(device)

In [34]:
x

tensor([6.1202e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])

## Autograd

The aurograde package provides automatic differentitation on all aperations on tensores. Generally speaking, torch.autograd is an engine for computing the vector Jacobian product. It computespartial derivatives while applying the chain rule.